version: '3.1'

services:

  service:
    container_name: event-sourcing
    build: .
    environment:
      DATABASE_URI: postgres://postgres:pwd@postgres:5432
    ports:
      - 80:8000
    volumes:
      - ./service:/service
    depends_on:
      - postgres
    command: gunicorn service:app -b 0.0.0.0:8000 --reload

  alembic:
    build: .
    environment:
      DATABASE_URI: postgres://postgres:pwd@postgres:5432
    volumes:
      - ./:/service
    depends_on:
      - postgres
    entrypoint: alembic

  pytest:
    build: .
    environment:
      DATABASE_URI: sqlite://
    volumes:
      - ./service:/service
    entrypoint: pytest

  postgres:
    container_name: event-sourcing-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd
