version: '3.1'

services:

  service:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./service:/service
    command: gunicorn service:app -b 0.0.0.0:8000 --reload

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pwd
