version: '3.1'

services:

  service:
    container_name: event-sourcing
    build: .
    ports:
      - 80:8000
    volumes:
      - ./service:/service
    command: gunicorn service:app -b 0.0.0.0:8000 --reload

  postgres:
    container_name: event-sourcing-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd
